#! python3
import logging
import random
import sys
import time

logger = logging.getLogger(__name__)
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)


def check_health():
    logger.debug("Service is healthy")

def get_user():
    user_id = random.randint(1000, 9999)
    logger.info(f"Response 200: GET /users/{user_id}")

def login():
    user_id = random.randint(1000, 9999)
    logger.info(f"Logged in with user ID {user_id}")

def get_user_error():
    user_id = random.randint(1000, 9999)
    logger.error(f"Response 404: User {user_id} not found. Is the database online?")


while True:
    if str(time.time())[-7:-2] == "00000":
        check_health()

    if random.random() > 0.999999:
        event = random.choices([get_user, login, get_user_error], weights=[0.7, .28, 0.02])[0]
        event()
